packages:
  - '.'

peerDependencyRules:
  allowedVersions:
    eslint: '10'

allowBuilds:
  canvas: true
  esbuild: true
  sharp: true
  unrs-resolver: true
  workerd: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
